### ISSUE TITLE
Change Password Text Hidden 

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#23]
The 'Change Password' text is hidden or inaccessible. you need to fix its visibility clearly.
![Uploading image.png…]()

**Comment by HemantaNeupane** [comment]
The picture is not loading in the issue. So I supposed the issue was on the page change password. 

The issue is shown in the screenshot below:
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119563887/b795adb5-8f47-41fb-8c47-4670f90ece1e)

The solved result looks like the following:
Some additional UI changes is also done
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119563887/515eaf60-2c1b-4e13-a4ca-bff656f2b6a3)
