### ISSUE TITLE
CSS not working in admin Dashboard

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#24]
CSS styles are not being applied correctly in the admin dashboard, impacting its functionality and appearance. Investigate and fix this issue urgently. 
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/14ca57a3-5074-4cd1-85c5-9a2129b77896)

**Comment by HemantaNeupane** [comment]
Dear Mr. Niroj Thapa,

I'm pleased to inform you that the issue regarding the CSS not working has successfully been resolved. Style was erased accidently which caused to that problem.
Below is a image showing were the problem was and the solved UI.
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119563887/ef042bc8-7d31-43fe-97db-7a0f622ad72b)
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119563887/48e23565-b3e6-44e1-a843-b2758c3f05ea)
